title: Blog of joseph-cb
author: Joseph
email: joseph@cerebras.net
description: > # this means to ignore newlines until "baseurl:"
  I am a firmware engineer in the embedded team.
  Badminton is my favorite sports.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
