title: Joseph's blog
author: Joseph Chan
email: joseph@cerebras.net
description: > # this means to ignore newlines until "baseurl:"
  I am a firmware engineer in the embedded team.
  Badminton is my favorite sports.

# social links
github_username:  joseph-cb # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
